
  {{ processor_name }}:
    image: ocrd/all:maximum
    command: {{ processor_name}} worker --database $MONGODB_URL --queue $RABBITMQ_URL
    depends_on:
      #- ocrd-processing-server
      - ocrd-mongodb
      - ocrd-rabbitmq
    volumes:
      - "$PWD/data:/data"
