
  {{ processor_name }}:
    image: ocrd/all:maximum
    container_name: {{ processor_name }}
    command: {{ processor_name}} worker --database $MONGODB_URL --queue $RABBITMQ_URL
    depends_on:
      #- ocrd-processing-server
      - ocrd-mongodb
      - ocrd-rabbitmq
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - "$PWD/data:/data"
    environment:
      - OCRD_NETWORK_LOGS_ROOT_DIR=/data/logs
