dest: ../../ocrd_all/tests/network/docker-compose.yml
dc_base_template: templates/docker-compose.template.ocrdall-tests.yaml
dc_service_template: templates/docker-compose.processor.template.ocrdall-tests.yaml
processors:
    ocrd-olena-binarize: "build:\n      context: ../../../ocrd_olena\n"
    ocrd-anybaseocr-crop: "build:\n      context: ../../../ocrd_anybaseocr\n"
    ocrd-cis-ocropy-denoise: "build:\n      context: ../../../ocrd_cis\n"
    ocrd-cis-ocropy-clip: "build:\n      context: ../../../ocrd_cis\n"
    ocrd-cis-ocropy-segment: "build:\n      context: ../../../ocrd_cis\n"
    ocrd-cis-ocropy-dewarp: "build:\n      context: ../../../ocrd_cis\n"
    ocrd-tesserocr-segment-region: "build:\n      context: ../../../ocrd_tesserocr\n"
    ocrd-tesserocr-recognize: "build:\n      context: ../../../ocrd_tesserocr\n"
    ocrd-segment-repair: "build:\n      context: ../../../ocrd_segment\n"
tesseract_vol_replacement: []
tessdata_prefix: /usr/local/share/tessdata
