dest: ../docker-compose.yaml
dc_base_template: templates/docker-compose.template.yaml
dc_service_template: templates/docker-compose.processor.template.yaml
processors:
    ocrd-olena-binarize: "build:\n      context: /home/jschrew/mygits/github/ocrd_olena-mein-fork/\n"
    ocrd-anybaseocr-crop: "build:\n      context: /home/jschrew/mygits/github/ocrd_anybaseocr-mein-fork/\n"
    ocrd-cis-ocropy-denoise: "build:\n      context: /home/jschrew/mygits/github/ocrd_cis-mein-fork/\n"
    ocrd-cis-ocropy-clip: "build:\n      context: /home/jschrew/mygits/github/ocrd_cis-mein-fork/\n"
    ocrd-cis-ocropy-segment: "build:\n      context: /home/jschrew/mygits/github/ocrd_cis-mein-fork/\n"
    ocrd-cis-ocropy-dewarp: "build:\n      context: /home/jschrew/mygits/github/ocrd_cis-mein-fork/\n"
    ocrd-tesserocr-segment-region: "build:\n      context: /home/jschrew/mygits/github/ocrd_tesserocr-mein-fork/\n"
    ocrd-tesserocr-recognize: "build:\n      context: /home/jschrew/mygits/github/ocrd_tesserocr-mein-fork/\n"
    ocrd-segment-repair: "build:\n      context: /home/jschrew/mygits/github/ocrd_segment-mein-fork/\n"
use_custom_logging_config: true
tesseract_vol_replacement: []
tessdata_prefix: /usr/local/share/tessdata
